//! Data plane: /v1/* request handlers + trace id propagation middleware (see docs/Architecture-backend.md).
//!
//! Responsibility layering:
//! - `trace_id_middleware` (outermost): reads/generates `x-request-id` → stores it in request extensions,
//!   echoes it back in the response header so clients can correlate the trace;
//! - `TraceIdSpan` / `TraceOnResponse`: the TraceLayer span carries trace_id and emits structured logs after the response;
//! - `chat_completions` / `models`: parse the request → call the proxy / model-list usecases → map errors to HTTP status codes.
//!
//! Streaming requests (`stream: true`) go through SSE passthrough: the event stream returned by the proxy
//! usecase is written frame by frame to the response body (`text/event-stream`); `[DONE]` is passed through
//! from upstream or synthesized by a conversion adapter, and the response ends when the stream ends; billing
//! and logging complete inline in the usecase when the stream ends.
//! Upstream keys are never returned: upstream error bodies are converged by the adapter into a generic error body (red line, see providers.rs).

use std::collections::VecDeque;
use std::sync::Arc;
use std::time::Duration;

use axum::body::Body;
use axum::body::Bytes;
use axum::extract::rejection::JsonRejection;
use axum::extract::{Request, State};
use axum::http::{HeaderMap, HeaderName, HeaderValue, StatusCode, header};
use axum::middleware::Next;
use axum::response::{IntoResponse, Response};
use axum::{Extension, Json};
use futures_util::StreamExt;
use serde_json::{Value, json};
use tower_http::trace::{MakeSpan, OnResponse};
use tracing::Span;
use uuid::Uuid;

use crate::domain::channel::ChannelRepository;
use crate::protocol::{CodecRegistry, ConversionContext, ProtocolError, ProtocolKind, StreamFrame};
use crate::usecases::models::ListModelsUsecase;
use crate::usecases::proxy::{ProxyError, ProxyRequest, ProxyRequestUsecase, ProxySuccess};

/// Data-plane shared state: injects the repositories needed by the proxy and model-list usecases (axum State).
#[derive(Clone)]
pub struct AppState {
    /// Proxy loop usecase (auth → channel selection → mapping → forwarding → billing → logging).
    pub proxy: Arc<ProxyRequestUsecase>,
    /// Channel repository needed by the model-list usecase (dedup for /v1/models).
    pub channel_repo: Arc<dyn ChannelRepository>,
    /// Optional knowledge repository used by knowledge and MCP service modules.
    pub knowledge_repo:
        Option<Arc<crate::infrastructure::sqlite::knowledge::SqliteKnowledgeRepository>>,
}

/// Trace id propagated through a request: written to request extensions by the middleware, shared by handlers / spans / log persistence.
#[derive(Debug, Clone)]
pub struct TraceId(pub String);

/// Client-injectable request ID header (echoed back when present, generated by the middleware otherwise). The http crate does not predefine this header name.
static X_REQUEST_ID: HeaderName = HeaderName::from_static("x-request-id");

/// Generate/reuse a trace id and propagate it through the request (outermost middleware, runs before the TraceLayer span is created).
pub(crate) async fn trace_id_middleware(mut request: Request, next: Next) -> Response {
    let trace_id = request
        .headers()
        .get(&X_REQUEST_ID)
        .and_then(|v| v.to_str().ok())
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
        .unwrap_or_else(|| Uuid::now_v7().to_string());
    request.extensions_mut().insert(TraceId(trace_id.clone()));
    let mut response = next.run(request).await;
    if let Ok(value) = HeaderValue::from_str(&trace_id) {
        response.headers_mut().insert(&X_REQUEST_ID, value);
    }
    response
}

/// TraceLayer span builder: reads the TraceId extension written by the middleware and carries it into the span fields.
#[derive(Clone)]
pub struct TraceIdSpan;

impl<B> MakeSpan<B> for TraceIdSpan {
    fn make_span(&mut self, request: &axum::http::Request<B>) -> Span {
        let trace_id = request
            .extensions()
            .get::<TraceId>()
            .map(|t| t.0.as_str())
            .unwrap_or("unknown");
        tracing::info_span!(
            "request",
            method = %request.method(),
            uri = %request.uri(),
            trace_id = %trace_id
        )
    }
}

/// Emit structured logs (status code + latency) inside the request span after the response completes.
#[derive(Clone)]
pub struct TraceOnResponse;

impl<B> OnResponse<B> for TraceOnResponse {
    fn on_response(self, response: &axum::http::Response<B>, latency: Duration, span: &Span) {
        span.in_scope(|| {
            tracing::debug!(
                status = response.status().as_u16(),
                latency_ms = latency.as_millis() as u64,
                "finished processing request"
            );
        });
    }
}

/// POST /v1/chat/completions: auth → proxy → billing → logging.
/// Non-streaming passes the response body through as-is; streaming writes the proxy usecase's event
/// stream frame by frame into the SSE response body (ending with `[DONE]`).
pub(crate) async fn chat_completions(
    State(state): State<AppState>,
    Extension(trace_id): Extension<TraceId>,
    headers: HeaderMap,
    body: Result<Json<Value>, JsonRejection>,
) -> Response {
    handle_protocol_request(ProtocolKind::OpenAiChat, state, trace_id, headers, body).await
}

pub(crate) async fn anthropic_messages(
    State(state): State<AppState>,
    Extension(trace_id): Extension<TraceId>,
    headers: HeaderMap,
    body: Result<Json<Value>, JsonRejection>,
) -> Response {
    handle_protocol_request(
        ProtocolKind::AnthropicMessages,
        state,
        trace_id,
        headers,
        body,
    )
    .await
}

pub(crate) async fn responses(
    State(state): State<AppState>,
    Extension(trace_id): Extension<TraceId>,
    headers: HeaderMap,
    body: Result<Json<Value>, JsonRejection>,
) -> Response {
    handle_protocol_request(
        ProtocolKind::OpenAiResponses,
        state,
        trace_id,
        headers,
        body,
    )
    .await
}

async fn handle_protocol_request(
    protocol: ProtocolKind,
    state: AppState,
    trace_id: TraceId,
    headers: HeaderMap,
    body: Result<Json<Value>, JsonRejection>,
) -> Response {
    let body = match body {
        Ok(Json(body)) => body,
        Err(rejection) => {
            return protocol_error_response(
                protocol,
                StatusCode::BAD_REQUEST,
                &rejection.body_text(),
            );
        }
    };
    let bearer_token = extract_local_api_key(protocol, &headers);
    if bearer_token.is_none() {
        return protocol_error_response(protocol, StatusCode::UNAUTHORIZED, "missing api key");
    }
    let context = ConversionContext {
        trace_id: trace_id.0.clone(),
        now_unix: current_unix_timestamp(),
    };
    let converted = match CodecRegistry::convert_request(protocol, body, &context) {
        Ok(converted) => converted,
        Err(err) => return protocol_conversion_error_response(protocol, err),
    };
    let request = ProxyRequest {
        bearer_token,
        model: converted
            .body
            .get("model")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string(),
        stream: converted.stream,
        body: converted.body,
        trace_id: trace_id.0,
    };
    match state.proxy.execute(request).await {
        Ok(ProxySuccess::NonStream(resp)) => {
            let status =
                StatusCode::from_u16(resp.status_code).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
            if !status.is_success() {
                if protocol == ProtocolKind::OpenAiChat {
                    return (
                        status,
                        [(header::CONTENT_TYPE, "application/json")],
                        resp.body,
                    )
                        .into_response();
                }
                return protocol_error_response(protocol, status, "upstream request failed");
            }
            let body = match serde_json::from_slice::<Value>(&resp.body) {
                Ok(value) => match CodecRegistry::convert_response(protocol, value, &context) {
                    Ok(converted) => match serde_json::to_vec(&converted.body) {
                        Ok(body) => body,
                        Err(err) => {
                            return protocol_error_response(
                                protocol,
                                StatusCode::INTERNAL_SERVER_ERROR,
                                &err.to_string(),
                            );
                        }
                    },
                    Err(err) => return protocol_conversion_error_response(protocol, err),
                },
                Err(_) if protocol == ProtocolKind::OpenAiChat => resp.body,
                Err(err) => {
                    return protocol_error_response(
                        protocol,
                        StatusCode::BAD_GATEWAY,
                        &format!("invalid canonical response: {err}"),
                    );
                }
            };
            (status, [(header::CONTENT_TYPE, "application/json")], body).into_response()
        }
        Ok(ProxySuccess::Stream(stream)) => {
            let resp_body = Body::from_stream(transform_proxy_stream(protocol, &context, stream));
            (
                StatusCode::OK,
                [
                    (header::CONTENT_TYPE, "text/event-stream"),
                    (header::CACHE_CONTROL, "no-cache"),
                ],
                resp_body,
            )
                .into_response()
        }
        Err(err) => proxy_error_response(protocol, err),
    }
}

/// GET /v1/models: merged, deduplicated models from enabled channels (consistent with the routable models of /v1/chat/completions).
pub(crate) async fn models(State(state): State<AppState>) -> Response {
    match ListModelsUsecase.execute(state.channel_repo.as_ref()).await {
        Ok(models) => {
            let data: Vec<Value> = models
                .into_iter()
                .map(|id| {
                    json!({
                        "id": id,
                        "object": "model",
                        "created": 0,
                        "owned_by": "revue-gate",
                    })
                })
                .collect();
            Json(json!({"object": "list", "data": data})).into_response()
        }
        Err(e) => {
            tracing::error!(error = %e, "failed to list models");
            error_response(StatusCode::INTERNAL_SERVER_ERROR, "failed to list models")
        }
    }
}

/// Extract the Bearer token from the Authorization header (strips the prefix; missing/invalid header → None, the auth usecase returns 401).
fn extract_bearer(headers: &HeaderMap) -> Option<String> {
    headers
        .get(header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|value| value.strip_prefix("Bearer "))
        .map(str::trim)
        .filter(|token| !token.is_empty())
        .map(str::to_string)
}

static X_API_KEY: HeaderName = HeaderName::from_static("x-api-key");

fn extract_local_api_key(protocol: ProtocolKind, headers: &HeaderMap) -> Option<String> {
    match protocol {
        ProtocolKind::AnthropicMessages => {
            extract_x_api_key(headers).or_else(|| extract_bearer(headers))
        }
        ProtocolKind::OpenAiChat | ProtocolKind::OpenAiResponses => extract_bearer(headers),
    }
}

fn extract_x_api_key(headers: &HeaderMap) -> Option<String> {
    headers
        .get(&X_API_KEY)
        .and_then(|v| v.to_str().ok())
        .map(str::trim)
        .filter(|token| !token.is_empty())
        .map(str::to_string)
}

/// OpenAI-style error response: `{"error": {"message": ..., "type": ...}}`, with type mapped from the status code to the OpenAI category.
fn error_response(status: StatusCode, message: &str) -> Response {
    (
        status,
        Json(json!({"error": {"message": message, "type": error_type(status)}})),
    )
        .into_response()
}

fn protocol_error_response(protocol: ProtocolKind, status: StatusCode, message: &str) -> Response {
    match protocol {
        ProtocolKind::AnthropicMessages => (
            status,
            Json(
                json!({"type": "error", "error": {"message": message, "type": error_type(status)}}),
            ),
        )
            .into_response(),
        ProtocolKind::OpenAiChat | ProtocolKind::OpenAiResponses => error_response(status, message),
    }
}

fn protocol_conversion_error_response(protocol: ProtocolKind, err: ProtocolError) -> Response {
    protocol_error_response(protocol, StatusCode::BAD_REQUEST, &err.to_string())
}

/// OpenAI error type mapping: downstream SDKs often branch on type (401→authentication_error,
/// 429→rate_limit_error, etc.); the gateway reuses the same classification for compatibility.
fn error_type(status: StatusCode) -> &'static str {
    match status {
        StatusCode::BAD_REQUEST => "invalid_request_error",
        StatusCode::UNAUTHORIZED => "authentication_error",
        StatusCode::FORBIDDEN => "permission_error",
        StatusCode::NOT_FOUND => "not_found_error",
        StatusCode::TOO_MANY_REQUESTS => "rate_limit_error",
        _ => "api_error",
    }
}

fn proxy_error_type(err: &ProxyError, status: StatusCode) -> &'static str {
    match err {
        ProxyError::SecurityPolicyBlocked => "security_policy_blocked",
        _ => error_type(status),
    }
}

/// Proxy error → status code + error body (401 / 429 / 404 / 502 / 500 / 400 mapped one-to-one to the usecase branches).
fn proxy_error_response(protocol: ProtocolKind, err: ProxyError) -> Response {
    let status = match &err {
        ProxyError::Unauthorized => StatusCode::UNAUTHORIZED,
        ProxyError::QuotaExceeded => StatusCode::TOO_MANY_REQUESTS,
        ProxyError::NoCandidateChannel(_) => StatusCode::NOT_FOUND,
        ProxyError::NoChannelAvailable { .. } | ProxyError::Provider(_) => StatusCode::BAD_GATEWAY,
        ProxyError::Repository(_) => StatusCode::INTERNAL_SERVER_ERROR,
        ProxyError::InvalidRequest(_) => StatusCode::BAD_REQUEST,
        ProxyError::SecurityPolicyBlocked => StatusCode::FORBIDDEN,
    };
    match protocol {
        ProtocolKind::AnthropicMessages => (
            status,
            Json(json!({"type": "error", "error": {"message": err.to_string(), "type": proxy_error_type(&err, status)}})),
        )
            .into_response(),
        ProtocolKind::OpenAiChat | ProtocolKind::OpenAiResponses => (
            status,
            Json(json!({"error": {"message": err.to_string(), "type": proxy_error_type(&err, status)}})),
        )
            .into_response(),
    }
}

fn current_unix_timestamp() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64
}

fn transform_proxy_stream(
    protocol: ProtocolKind,
    context: &ConversionContext,
    stream: futures_util::stream::BoxStream<
        'static,
        Result<crate::domain::provider::StreamEvent, ProxyError>,
    >,
) -> impl futures_util::Stream<Item = Result<Bytes, std::convert::Infallible>> + Send + 'static {
    struct State {
        stream: futures_util::stream::BoxStream<
            'static,
            Result<crate::domain::provider::StreamEvent, ProxyError>,
        >,
        transformer: Box<dyn crate::protocol::StreamTransformer + Send>,
        pending: VecDeque<StreamFrame>,
        finished: bool,
    }

    let transformer = CodecRegistry::stream_transformer(protocol, context);
    futures_util::stream::unfold(
        State {
            stream,
            transformer,
            pending: VecDeque::new(),
            finished: false,
        },
        |mut state| async move {
            loop {
                if let Some(frame) = state.pending.pop_front() {
                    return Some((Ok(frame.bytes), state));
                }
                if state.finished {
                    return None;
                }
                match state.stream.next().await {
                    Some(Ok(event)) => {
                        match state.transformer.transform_chunk(Bytes::from(event.data)) {
                            Ok(frames) => state.pending.extend(frames),
                            Err(_) => {
                                return None;
                            }
                        }
                    }
                    Some(Err(_)) => {
                        return None;
                    }
                    None => match state.transformer.finish() {
                        Ok(frames) => {
                            state.pending.extend(frames);
                            state.finished = true;
                        }
                        Err(_) => {
                            return None;
                        }
                    },
                }
            }
        },
    )
}

#[cfg(test)]
mod tests {
    use std::sync::{Arc, Mutex};

    use axum::Router;
    use axum::body::{Body, Bytes};
    use axum::extract::Json;
    use axum::http::{Request, StatusCode, header};
    use axum::routing::post;
    use serde_json::Value;
    use sqlx::Row;
    use tower::ServiceExt;

    use super::*;
    use crate::domain::api_key::{ApiKeyRepository, Quota};
    use crate::domain::channel::{Channel, ChannelRepository, ChannelType};
    use crate::domain::settings::GatewaySettings;
    use crate::infrastructure::providers::adaptor_for;
    use crate::infrastructure::providers::test_util;
    use crate::infrastructure::sqlite::api_key::SqliteApiKeyRepository;
    use crate::infrastructure::sqlite::channel::SqliteChannelRepository;
    use crate::infrastructure::sqlite::init_pool;
    use crate::infrastructure::sqlite::request_log::SqliteRequestLogRepository;
    use crate::interface::http::router::build_router;
    use crate::test_support::sample_api_key;

    /// OpenAI-compatible non-streaming response sample (with usage) for the mock upstream to return.
    fn chat_completion_response() -> Value {
        serde_json::json!({
            "id": "chatcmpl-123",
            "object": "chat.completion",
            "created": 1700000000,
            "model": "gpt-4o",
            "choices": [{
                "index": 0,
                "message": {"role": "assistant", "content": "hello"},
                "finish_reason": "stop",
            }],
            "usage": {"prompt_tokens": 10, "completion_tokens": 5, "total_tokens": 15},
        })
    }

    /// seam B test harness: real SQLite (in-memory) + real sqlx repositories + real adapters.
    struct Harness {
        pool: sqlx::SqlitePool,
        channel_repo: Arc<SqliteChannelRepository>,
        api_key_repo: Arc<SqliteApiKeyRepository>,
        log_repo: Arc<SqliteRequestLogRepository>,
    }

    async fn harness() -> Harness {
        let pool = init_pool("sqlite::memory:").await.expect("init pool");
        let channel_repo = Arc::new(SqliteChannelRepository::new(pool.clone()));
        let api_key_repo = Arc::new(SqliteApiKeyRepository::new(pool.clone()));
        let log_repo = Arc::new(SqliteRequestLogRepository::new(pool.clone()));
        Harness {
            pool,
            channel_repo,
            api_key_repo,
            log_repo,
        }
    }

    /// Build the data-plane router (real usecases + real adapter resolution, channel base_url pointing at the mock upstream).
    fn app(h: &Harness) -> Router {
        app_with_settings(h, GatewaySettings::default())
    }

    fn app_with_settings(h: &Harness, settings: GatewaySettings) -> Router {
        let usecase = ProxyRequestUsecase::new(
            Arc::clone(&h.api_key_repo) as Arc<dyn ApiKeyRepository>,
            Arc::clone(&h.channel_repo) as Arc<dyn ChannelRepository>,
            Arc::clone(&h.log_repo) as Arc<dyn crate::domain::request_log::RequestLogRepository>,
            Box::new(|c: &Channel| adaptor_for(c.channel_type)),
            Arc::new(std::sync::RwLock::new(settings.clone())),
        );
        let state = AppState {
            proxy: Arc::new(usecase),
            knowledge_repo: None,
            channel_repo: Arc::clone(&h.channel_repo) as Arc<dyn ChannelRepository>,
        };
        build_router(state, &settings)
    }

    /// Save an enabled channel pointing at the mock upstream (model gpt-4o) plus one valid local key, returning the key plaintext.
    async fn seed_channel_and_key(h: &Harness, base_url: &str) -> String {
        let mut channel = test_util::test_channel(ChannelType::OpenAi, base_url);
        channel.models = vec!["gpt-4o".to_string()];
        h.channel_repo.save(&channel).await.expect("save channel");
        let key = sample_api_key();
        h.api_key_repo.save(&key).await.expect("save key");
        key.key
    }

    fn post_chat(body: &str, bearer: Option<&str>, trace_id: &str) -> Request<Body> {
        let mut builder = Request::builder()
            .method("POST")
            .uri("/v1/chat/completions")
            .header(header::CONTENT_TYPE, "application/json")
            .header("x-request-id", trace_id);
        if let Some(bearer) = bearer {
            builder = builder.header(header::AUTHORIZATION, format!("Bearer {bearer}"));
        }
        builder
            .body(Body::from(body.to_string()))
            .expect("build request")
    }

    async fn error_type(response: Response) -> String {
        let body: Value = serde_json::from_slice(
            &axum::body::to_bytes(response.into_body(), usize::MAX)
                .await
                .expect("read body"),
        )
        .expect("json");
        body["error"]["type"]
            .as_str()
            .expect("error type")
            .to_string()
    }

    /// MakeWriter that captures the fmt subscriber output into a shared buffer (structured-log test harness).
    #[derive(Clone, Default)]
    struct Capture(Arc<Mutex<Vec<u8>>>);

    impl std::io::Write for Capture {
        fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
            self.0
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner())
                .extend_from_slice(buf);
            Ok(buf.len())
        }
        fn flush(&mut self) -> std::io::Result<()> {
            Ok(())
        }
    }

    impl tracing_subscriber::fmt::MakeWriter<'_> for Capture {
        type Writer = Capture;
        fn make_writer(&self) -> Self::Writer {
            self.clone()
        }
    }

    /// seam B closed loop: real network forwarding to a mock upstream → response passed through as-is, request log
    /// persisted (trace_id matches), quota accumulated from usage total, and `x-request-id` echoed back.
    #[tokio::test]
    async fn chat_completions_forwards_records_log_accumulates_quota_and_echoes_trace() {
        let h = harness().await;

        // Mock upstream: records the received request body and returns a completion response with usage.
        let received: Arc<Mutex<Option<Value>>> = Arc::new(Mutex::new(None));
        let probe = received.clone();
        let upstream = Router::new().route(
            "/chat/completions",
            post(move |body: Json<Value>| async move {
                *probe.lock().unwrap() = Some(body.0);
                Json(chat_completion_response())
            }),
        );
        let (base, handle) = test_util::spawn(upstream).await;

        let key = seed_channel_and_key(&h, &base).await;
        let app = app(&h);

        let response = app
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","messages":[{"role":"user","content":"hi"}]}"#,
                Some(&key),
                "trace-123",
            ))
            .await
            .expect("oneshot");

        handle.abort();
        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response
                .headers()
                .get("x-request-id")
                .map(|v| v.to_str().unwrap()),
            Some("trace-123"),
            "trace id 应原样回传给客户端"
        );

        // Upstream received the rewritten request body (model passed through).
        let sent = received
            .lock()
            .unwrap()
            .clone()
            .expect("upstream received body");
        assert_eq!(sent["model"], "gpt-4o");

        // Response body passed through as-is (choices content comes from upstream).
        let body: Value = serde_json::from_slice(
            &axum::body::to_bytes(response.into_body(), usize::MAX)
                .await
                .expect("read body"),
        )
        .expect("json");
        assert_eq!(body["choices"][0]["message"]["content"], "hello");

        // Request log persisted: trace_id / status code / model / usage match the request.
        let row =
            sqlx::query("SELECT trace_id, status_code, model, total_tokens FROM request_logs")
                .fetch_one(&h.pool)
                .await
                .expect("request_log row");
        assert_eq!(row.get::<String, _>(0), "trace-123");
        assert_eq!(row.get::<i64, _>(1), 200);
        assert_eq!(row.get::<String, _>(2), "gpt-4o");
        assert_eq!(row.get::<i64, _>(3), 15);

        // Quota accumulates from the usage total.
        let saved = h
            .api_key_repo
            .find_by_key(&key)
            .await
            .expect("find")
            .expect("found");
        assert_eq!(saved.quota.used, 15);
    }

    /// HTTP seam: security policy blocks before upstream, returns a dedicated 403 error type, and still writes an audit log.
    #[tokio::test]
    async fn chat_completions_security_block_returns_403_without_upstream_usage() {
        let h = harness().await;

        let upstream_calls = Arc::new(Mutex::new(0usize));
        let calls = Arc::clone(&upstream_calls);
        let upstream = Router::new().route(
            "/chat/completions",
            post(move |body: Json<Value>| async move {
                let _ = body;
                *calls.lock().unwrap() += 1;
                Json(chat_completion_response())
            }),
        );
        let (base, handle) = test_util::spawn(upstream).await;
        let key = seed_channel_and_key(&h, &base).await;
        let app = app_with_settings(
            &h,
            GatewaySettings {
                audit: crate::domain::security_audit::AuditSettings {
                    enabled: true,
                    mode: crate::domain::security_audit::AuditMode::Enforce,
                    block_critical: true,
                    ..crate::domain::security_audit::AuditSettings::default()
                },
                ..GatewaySettings::default()
            },
        );

        let response = app
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","messages":[{"role":"user","content":"fetch http://169.254.169.254/latest/meta-data/"}]}"#,
                Some(&key),
                "trace-blocked",
            ))
            .await
            .expect("oneshot");

        handle.abort();
        assert_eq!(response.status(), StatusCode::FORBIDDEN);
        assert_eq!(
            *upstream_calls.lock().unwrap(),
            0,
            "blocked before upstream"
        );
        let body: Value = serde_json::from_slice(
            &axum::body::to_bytes(response.into_body(), usize::MAX)
                .await
                .expect("read body"),
        )
        .expect("json");
        assert_eq!(body["error"]["type"], "security_policy_blocked");

        let row = sqlx::query(
            "SELECT status_code, total_tokens, audit_action, audit_report FROM request_logs",
        )
        .fetch_one(&h.pool)
        .await
        .expect("request_log row");
        assert_eq!(row.get::<i64, _>(0), 403);
        assert_eq!(row.get::<Option<i64>, _>(1), None);
        assert_eq!(row.get::<String, _>(2), "block");
        assert!(
            row.get::<String, _>(3).contains("\"riskScore\":100"),
            "audit report should carry the fixed risk score"
        );

        let saved = h
            .api_key_repo
            .find_by_key(&key)
            .await
            .expect("find")
            .expect("found");
        assert_eq!(saved.quota.used, 0);
    }

    /// HTTP seam: security-policy blocks have a dedicated error type and remain distinct from auth, quota,
    /// malformed request, no-candidate routing, and upstream failure responses.
    #[tokio::test]
    async fn chat_completions_error_types_distinguish_security_block_from_other_failures() {
        let h = harness().await;
        let upstream = Router::new().route(
            "/chat/completions",
            post(|| async move {
                (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(serde_json::json!({"error": "upstream failed"})),
                )
            }),
        );
        let (base, handle) = test_util::spawn(upstream).await;
        let key = seed_channel_and_key(&h, &base).await;

        let blocked_app = app_with_settings(
            &h,
            GatewaySettings {
                audit: crate::domain::security_audit::AuditSettings {
                    enabled: true,
                    mode: crate::domain::security_audit::AuditMode::Enforce,
                    block_critical: true,
                    ..crate::domain::security_audit::AuditSettings::default()
                },
                ..GatewaySettings::default()
            },
        );
        let blocked = blocked_app
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","messages":[{"role":"user","content":"fetch http://169.254.169.254/latest/meta-data/"}]}"#,
                Some(&key),
                "trace-error-type-blocked",
            ))
            .await
            .expect("blocked response");
        assert_eq!(blocked.status(), StatusCode::FORBIDDEN);
        assert_eq!(error_type(blocked).await, "security_policy_blocked");

        let missing_bearer = app(&h)
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","messages":[]}"#,
                None,
                "trace-error-type-auth",
            ))
            .await
            .expect("auth response");
        assert_eq!(missing_bearer.status(), StatusCode::UNAUTHORIZED);
        assert_eq!(error_type(missing_bearer).await, "authentication_error");

        let mut exhausted = h
            .api_key_repo
            .find_by_key(&key)
            .await
            .expect("find")
            .expect("found");
        exhausted.quota = Quota {
            limit: Some(0),
            used: 0,
        };
        h.api_key_repo
            .save(&exhausted)
            .await
            .expect("save exhausted key");
        let quota = app(&h)
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","messages":[]}"#,
                Some(&key),
                "trace-error-type-quota",
            ))
            .await
            .expect("quota response");
        assert_eq!(quota.status(), StatusCode::TOO_MANY_REQUESTS);
        assert_eq!(error_type(quota).await, "rate_limit_error");

        exhausted.quota = Quota {
            limit: Some(100),
            used: 0,
        };
        h.api_key_repo
            .save(&exhausted)
            .await
            .expect("restore key quota");
        let invalid = app(&h)
            .oneshot(post_chat(
                "not-json",
                Some(&key),
                "trace-error-type-invalid",
            ))
            .await
            .expect("invalid response");
        assert_eq!(invalid.status(), StatusCode::BAD_REQUEST);
        assert_eq!(error_type(invalid).await, "invalid_request_error");

        let no_candidate = app(&h)
            .oneshot(post_chat(
                r#"{"model":"claude-3","messages":[]}"#,
                Some(&key),
                "trace-error-type-no-candidate",
            ))
            .await
            .expect("no candidate response");
        assert_eq!(no_candidate.status(), StatusCode::NOT_FOUND);
        assert_eq!(error_type(no_candidate).await, "not_found_error");

        let upstream_failure = app(&h)
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","messages":[]}"#,
                Some(&key),
                "trace-error-type-upstream",
            ))
            .await
            .expect("upstream failure response");
        handle.abort();
        assert_eq!(upstream_failure.status(), StatusCode::BAD_GATEWAY);
        assert_eq!(error_type(upstream_failure).await, "api_error");
    }

    /// No Bearer → 401, and no request log is written.
    #[tokio::test]
    async fn chat_completions_without_bearer_returns_401() {
        let h = harness().await;
        let app = app(&h);

        let response = app
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","messages":[]}"#,
                None,
                "trace-no-bearer",
            ))
            .await
            .expect("oneshot");

        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
        let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM request_logs")
            .fetch_one(&h.pool)
            .await
            .expect("count logs");
        assert_eq!(count, 0, "认证失败不写日志");
    }

    /// Invalid Bearer (not present in the repository) → 401.
    #[tokio::test]
    async fn chat_completions_with_invalid_bearer_returns_401() {
        let h = harness().await;
        let app = app(&h);

        let response = app
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","messages":[]}"#,
                Some("sk-revue-ffffffffffffffff"),
                "trace-invalid-bearer",
            ))
            .await
            .expect("oneshot");

        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    /// seam B: streaming request (stream=true) → real reqwest hits a mock upstream, SSE frames relayed frame by frame,
    /// `[DONE]` terminates correctly; after the stream, bill by usage and write a success log (is_stream=true).
    #[tokio::test]
    async fn chat_completions_streaming_relays_sse_and_done_and_bills() {
        let h = harness().await;

        // Mock upstream: returns a complete OpenAI-compatible SSE stream (delta frames + trailing usage frame + [DONE]).
        let payload = concat!(
            "data: {\"id\":\"chatcmpl-1\",\"object\":\"chat.completion.chunk\",",
            "\"choices\":[{\"index\":0,\"delta\":{\"content\":\"Hello\"}}]}\n\n",
            "data: {\"id\":\"chatcmpl-1\",\"object\":\"chat.completion.chunk\",",
            "\"choices\":[{\"index\":0,\"delta\":{\"content\":\" world\"}}]}\n\n",
            "data: {\"id\":\"chatcmpl-1\",\"object\":\"chat.completion.chunk\",",
            "\"choices\":[{\"index\":0,\"delta\":{},\"finish_reason\":\"stop\"}],",
            "\"usage\":{\"prompt_tokens\":3,\"completion_tokens\":2,\"total_tokens\":5}}\n\n",
            "data: [DONE]\n\n",
        );
        let upstream = Router::new().route(
            "/chat/completions",
            post(move || async move {
                (
                    StatusCode::OK,
                    [(header::CONTENT_TYPE, "text/event-stream")],
                    Body::from(payload),
                )
            }),
        );
        let (base, handle) = test_util::spawn(upstream).await;

        let key = seed_channel_and_key(&h, &base).await;
        let app = app(&h);

        let response = app
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","stream":true,"messages":[{"role":"user","content":"hi"}]}"#,
                Some(&key),
                "trace-stream-1",
            ))
            .await
            .expect("oneshot");

        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response
                .headers()
                .get(header::CONTENT_TYPE)
                .map(|v| v.to_str().unwrap()),
            Some("text/event-stream"),
            "SSE 响应应带 text/event-stream"
        );

        // Close the mock upstream only after reading the whole response body, to avoid truncating a stream still in flight.
        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .expect("read body");
        handle.abort();
        let text = String::from_utf8_lossy(&body);
        assert_eq!(text, payload, "SSE 帧原样透传，不改写增量内容");
        assert!(
            text.ends_with("data: [DONE]\n\n"),
            "[DONE] 收尾正确；实际：{text}"
        );

        // Stream ended: bill usage + write a success log (is_stream=true, total_tokens from the aggregated usage).
        let row =
            sqlx::query("SELECT trace_id, status_code, is_stream, total_tokens FROM request_logs")
                .fetch_one(&h.pool)
                .await
                .expect("request_log row");
        assert_eq!(row.get::<String, _>(0), "trace-stream-1");
        assert_eq!(row.get::<i64, _>(1), 200);
        assert_eq!(row.get::<i64, _>(2), 1, "is_stream 应标记为真");
        assert_eq!(row.get::<i64, _>(3), 5);

        let saved = h
            .api_key_repo
            .find_by_key(&key)
            .await
            .expect("find")
            .expect("found");
        assert_eq!(saved.quota.used, 5, "流式 usage 累加配额");
    }

    /// seam B: upstream connection breaks mid-stream (no `[DONE]`) → the client sees a truncated stream after the
    /// already-sent frames pass through as-is (headers already sent, status stays 200); the usecase writes a 502
    /// failure log and has billed the incremental usage. Only this seam reliably covers mid-stream interruption and termination (Spec §Testing Decisions).
    #[tokio::test]
    async fn chat_completions_streaming_interruption_truncates_and_bills_partial_usage() {
        let h = harness().await;

        // Mock upstream: emits delta frames + a usage frame, then injects an error mid-stream (connection reset, no [DONE]).
        // A short sleep after each frame: ensure the gateway has received the response headers and opened the stream,
        // and frames were reliably read before the disconnect (RST drops in-flight bytes, so the error must lag the last frame).
        let frame_delta = "data: {\"id\":\"chatcmpl-1\",\"object\":\"chat.completion.chunk\",\"choices\":[{\"index\":0,\"delta\":{\"content\":\"Hello\"}}]}\n\n";
        let frame_usage = "data: {\"id\":\"chatcmpl-1\",\"object\":\"chat.completion.chunk\",\"choices\":[{\"index\":0,\"delta\":{},\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":3,\"completion_tokens\":2,\"total_tokens\":5}}\n\n";
        let upstream = Router::new().route(
            "/chat/completions",
            post(move || async move {
                (
                    StatusCode::OK,
                    [(header::CONTENT_TYPE, "text/event-stream")],
                    Body::from_stream(futures_util::stream::unfold(0u8, move |step| async move {
                        match step {
                            0 => Some((
                                Ok::<_, std::io::Error>(Bytes::from_static(frame_delta.as_bytes())),
                                1,
                            )),
                            1 => {
                                tokio::time::sleep(std::time::Duration::from_millis(50)).await;
                                Some((
                                    Ok::<_, std::io::Error>(Bytes::from_static(
                                        frame_usage.as_bytes(),
                                    )),
                                    2,
                                ))
                            }
                            2 => {
                                tokio::time::sleep(std::time::Duration::from_millis(50)).await;
                                Some((
                                    Err::<_, std::io::Error>(std::io::Error::other(
                                        "upstream connection reset",
                                    )),
                                    3,
                                ))
                            }
                            _ => None,
                        }
                    })),
                )
            }),
        );
        let (base, handle) = test_util::spawn(upstream).await;

        let key = seed_channel_and_key(&h, &base).await;
        let app = app(&h);

        let response = app
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","stream":true,"messages":[{"role":"user","content":"hi"}]}"#,
                Some(&key),
                "trace-stream-err",
            ))
            .await
            .expect("oneshot");

        assert_eq!(
            response.status(),
            StatusCode::OK,
            "响应头已发出，流中断无法改为 502"
        );
        assert_eq!(
            response
                .headers()
                .get(header::CONTENT_TYPE)
                .map(|v| v.to_str().unwrap()),
            Some("text/event-stream"),
            "SSE 响应应带 text/event-stream"
        );

        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .expect("read body");
        handle.abort();
        let text = String::from_utf8_lossy(&body);
        assert_eq!(
            text,
            format!("{frame_delta}{frame_usage}"),
            "已下发的帧原样透传后截断；实际：{text}"
        );
        assert!(
            !text.contains("[DONE]"),
            "流中断：客户端不应看到 [DONE] 收尾；实际：{text}"
        );

        // Usecase side: 502 failure log (with incremental usage) + billing from the incremental usage.
        let row = sqlx::query(
            "SELECT trace_id, status_code, is_stream, total_tokens, error_message FROM request_logs",
        )
        .fetch_one(&h.pool)
        .await
        .expect("request_log row");
        assert_eq!(row.get::<String, _>(0), "trace-stream-err");
        assert_eq!(
            row.get::<i64, _>(1),
            502,
            "流中断写失败日志（与线上 200 分离）"
        );
        assert_eq!(row.get::<i64, _>(2), 1, "is_stream 应标记为真");
        assert_eq!(row.get::<i64, _>(3), 5, "失败日志携带已聚合的增量 usage");
        assert!(
            row.get::<Option<String>, _>(4).is_some(),
            "流中断应记录失败原因"
        );

        let saved = h
            .api_key_repo
            .find_by_key(&key)
            .await
            .expect("find")
            .expect("found");
        assert_eq!(
            saved.quota.used, 5,
            "流中断时已下发的增量 usage 同样累加配额"
        );
    }

    /// stream=true without a Bearer → 401: auth precedes feature gates (the "no Bearer returns 401" requirement has no streaming exemption).
    #[tokio::test]
    async fn chat_completions_streaming_without_bearer_returns_401() {
        let h = harness().await;
        let app = app(&h);

        let response = app
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","stream":true,"messages":[]}"#,
                None,
                "trace-stream-no-bearer",
            ))
            .await
            .expect("oneshot");

        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
    }

    /// seam B: quota exceeded → 429 (Spec-implementation §Testing Decisions requires seam B to cover quota).
    #[tokio::test]
    async fn chat_completions_quota_exceeded_returns_429() {
        let h = harness().await;
        // A placeholder channel URL suffices: quota checks run before channel selection/forwarding, so upstream is never reached.
        let key_str = seed_channel_and_key(&h, "https://api.openai.com/v1").await;
        let mut key = h
            .api_key_repo
            .find_by_key(&key_str)
            .await
            .expect("find")
            .expect("found");
        key.quota = Quota {
            limit: Some(0),
            used: 0,
        };
        h.api_key_repo.save(&key).await.expect("save exhausted key");

        let response = app(&h)
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","messages":[{"role":"user","content":"hi"}]}"#,
                Some(&key_str),
                "trace-quota",
            ))
            .await
            .expect("oneshot");

        assert_eq!(response.status(), StatusCode::TOO_MANY_REQUESTS);
    }

    /// Structured logs carry the trace id end to end (requirement checkbox 4): the TraceLayer span carries x-request-id.
    /// 401 requests also go through the TraceLayer — the span is created before auth, so the trace id appears in the formatted logs.
    #[tokio::test]
    async fn structured_log_span_carries_trace_id() {
        let h = harness().await;
        let app = app(&h);

        // Install a fmt subscriber capturing output to a shared buffer; this is the only place in the whole test process that installs the global default subscriber.
        let capture = Capture::default();
        let subscriber = tracing_subscriber::fmt()
            .with_writer(capture.clone())
            .with_max_level(tracing::Level::DEBUG)
            .finish();
        tracing::subscriber::set_global_default(subscriber)
            .expect("only this test installs a global tracing subscriber");

        let _response = app
            .oneshot(post_chat(
                r#"{"model":"gpt-4o","messages":[]}"#,
                None,
                "trace-captured-1",
            ))
            .await
            .expect("oneshot");

        let logs = String::from_utf8(capture.0.lock().unwrap_or_else(|p| p.into_inner()).clone())
            .expect("utf8 logs");
        assert!(
            logs.contains("trace-captured-1"),
            "结构化日志应携带 trace id；实际输出：\n{logs}"
        );
    }

    /// Malformed JSON → 400.
    #[tokio::test]
    async fn chat_completions_malformed_json_returns_400() {
        let h = harness().await;
        let app = app(&h);

        let response = app
            .oneshot(post_chat("not-json", Some("whatever"), "trace-bad-json"))
            .await
            .expect("oneshot");

        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
    }

    /// GET /v1/models: merged, deduplicated models from enabled channels only.
    #[tokio::test]
    async fn models_lists_enabled_channel_models() {
        let h = harness().await;
        let mut a = test_util::test_channel(ChannelType::OpenAi, "https://api.openai.com/v1");
        a.name = "a".to_string();
        a.models = vec!["gpt-4o".to_string(), "claude-3".to_string()];
        h.channel_repo.save(&a).await.expect("save a");
        let mut b = test_util::test_channel(ChannelType::OpenAi, "https://api.openai.com/v1");
        b.name = "b".to_string();
        b.models = vec!["gpt-4o".to_string()];
        b.enabled = false;
        h.channel_repo.save(&b).await.expect("save b");

        let app = app(&h);
        let response = app
            .oneshot(
                Request::builder()
                    .uri("/v1/models")
                    .body(Body::empty())
                    .expect("build request"),
            )
            .await
            .expect("oneshot");

        assert_eq!(response.status(), StatusCode::OK);
        let body: Value = serde_json::from_slice(
            &axum::body::to_bytes(response.into_body(), usize::MAX)
                .await
                .expect("read body"),
        )
        .expect("json");
        let ids: Vec<&str> = body["data"]
            .as_array()
            .expect("data array")
            .iter()
            .map(|m| m["id"].as_str().expect("model id"))
            .collect();
        assert_eq!(ids, vec!["gpt-4o", "claude-3"], "禁用渠道的模型被剔除");
    }
}
