//! API key management use cases: CRUD / enable-disable / quota management orchestration.
//!
//! Stateless use cases: repositories are injected as `&dyn ApiKeyRepository`, seam A tests can use in-memory mocks.
//! Key format `sk-revue-<16 hex chars>` (8 bytes of entropy, generated by the OS-level getrandom source);
//! the key plaintext is only visible at creation; updates never change the key. Quota management: a limit is configurable,
//! and used quota accumulates per request and is persisted (`AccumulateUsageUsecase`, called after a successful proxy). Over-limit decisions are handled by QuotaPolicy.

use chrono::Utc;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::domain::api_key::{ApiKey, ApiKeyRepository, Quota};
use crate::domain::error::RepositoryError;

/// API key use case layer error.
#[derive(Debug, thiserror::Error)]
pub enum ApiKeyError {
    #[error("api key not found")]
    NotFound,
    #[error("invalid api key: {0}")]
    Validation(String),
    #[error("api key repository error: {0}")]
    Repository(#[from] RepositoryError),
}

/// Input for creating / editing a key (shared by create and update; the key itself cannot be specified via input).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiKeyInput {
    pub name: String,
    /// Quota limit; None means unlimited.
    pub quota_limit: Option<u64>,
    pub enabled: bool,
}

/// Create a key: generate a new `sk-revue-<16 hex>` key and save it, returning the entity with the full plaintext (shown once).
pub struct CreateApiKeyUsecase;
impl CreateApiKeyUsecase {
    pub async fn execute(
        &self,
        repo: &dyn ApiKeyRepository,
        input: ApiKeyInput,
    ) -> Result<ApiKey, ApiKeyError> {
        let input = normalize(input)?;
        let now = Utc::now();
        let api_key = ApiKey {
            id: Uuid::now_v7(),
            name: input.name,
            key: generate_key(),
            enabled: input.enabled,
            quota: Quota {
                limit: input.quota_limit,
                used: 0,
            },
            created_at: now,
            updated_at: now,
        };
        repo.save(&api_key).await?;
        Ok(api_key)
    }
}

/// Update a key: load the original entity → merge the input (name / quota limit / enable state; the key stays unchanged) → save.
pub struct UpdateApiKeyUsecase;
impl UpdateApiKeyUsecase {
    pub async fn execute(
        &self,
        repo: &dyn ApiKeyRepository,
        id: Uuid,
        input: ApiKeyInput,
    ) -> Result<ApiKey, ApiKeyError> {
        let input = normalize(input)?;
        let mut api_key = repo.find_by_id(id).await?.ok_or(ApiKeyError::NotFound)?;
        api_key.name = input.name;
        api_key.quota.limit = input.quota_limit;
        api_key.enabled = input.enabled;
        api_key.updated_at = Utc::now();
        repo.save(&api_key).await?;
        Ok(api_key)
    }
}
/// Delete a key; returns `NotFound` if missing.
pub struct DeleteApiKeyUsecase;
impl DeleteApiKeyUsecase {
    pub async fn execute(&self, repo: &dyn ApiKeyRepository, id: Uuid) -> Result<(), ApiKeyError> {
        repo.delete(id).await.map_err(map_repo_error)?;
        Ok(())
    }
}

/// List all keys.
pub struct ListApiKeysUsecase;
impl ListApiKeysUsecase {
    pub async fn execute(&self, repo: &dyn ApiKeyRepository) -> Result<Vec<ApiKey>, ApiKeyError> {
        Ok(repo.list().await?)
    }
}

/// Enable / disable a key: set `enabled` and persist.
pub struct SetApiKeyEnabledUsecase;
impl SetApiKeyEnabledUsecase {
    pub async fn execute(
        &self,
        repo: &dyn ApiKeyRepository,
        id: Uuid,
        enabled: bool,
    ) -> Result<ApiKey, ApiKeyError> {
        let mut api_key = repo.find_by_id(id).await?.ok_or(ApiKeyError::NotFound)?;
        api_key.enabled = enabled;
        api_key.updated_at = Utc::now();
        repo.save(&api_key).await?;
        Ok(api_key)
    }
}

/// Accumulate used quota and persist (billed against the parsed usage after a successful proxy; saturating add prevents overflow).
pub struct AccumulateUsageUsecase;
impl AccumulateUsageUsecase {
    pub async fn execute(
        &self,
        repo: &dyn ApiKeyRepository,
        api_key_id: Uuid,
        tokens: u64,
    ) -> Result<ApiKey, ApiKeyError> {
        let mut api_key = repo
            .find_by_id(api_key_id)
            .await?
            .ok_or(ApiKeyError::NotFound)?;
        api_key.quota.used = api_key.quota.used.saturating_add(tokens);
        api_key.updated_at = Utc::now();
        repo.save(&api_key).await?;
        Ok(api_key)
    }
}

/// Normalize input: trim the name (a blank name errors).
fn normalize(input: ApiKeyInput) -> Result<ApiKeyInput, ApiKeyError> {
    let name = input.name.trim();
    if name.is_empty() {
        return Err(ApiKeyError::Validation("name must not be empty".into()));
    }
    Ok(ApiKeyInput {
        name: name.to_string(),
        ..input
    })
}

/// Generate `sk-revue-<16 random hex>`: 8 bytes from the OS-level random source (getrandom).
fn generate_key() -> String {
    let mut bytes = [0u8; 8];
    getrandom::fill(&mut bytes).expect("OS random number generator is available");
    let hex: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
    format!("sk-revue-{hex}")
}

/// Map a repository error to a use case error: `NotFound` is semantically the same as the use case's `NotFound`.
fn map_repo_error(e: RepositoryError) -> ApiKeyError {
    match e {
        RepositoryError::NotFound => ApiKeyError::NotFound,
        other => ApiKeyError::Repository(other),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_support::InMemoryApiKeyRepository;

    /// Build a sample creation input.
    fn input(name: &str) -> ApiKeyInput {
        ApiKeyInput {
            name: name.to_string(),
            quota_limit: Some(100),
            enabled: true,
        }
    }

    /// Key format: `sk-revue-` prefix + 16 lowercase hex chars (25 chars, 8 bytes of entropy).
    #[tokio::test]
    async fn create_generates_sk_revue_key_with_16_hex_chars() {
        let repo = InMemoryApiKeyRepository::new();
        let created = CreateApiKeyUsecase
            .execute(&repo, input("my-client"))
            .await
            .expect("create");

        let Some(hex_part) = created.key.strip_prefix("sk-revue-") else {
            panic!("key should start with sk-revue-: {}", created.key);
        };
        assert_eq!(hex_part.len(), 16, "hex 部分应为 16 位");
        assert!(
            hex_part.chars().all(|c| c.is_ascii_hexdigit()),
            "hex 部分应全为 hex 字符: {hex_part}"
        );
        assert_eq!(created.key.len(), 25);
        assert_eq!(
            created.quota,
            Quota {
                limit: Some(100),
                used: 0
            }
        );

        let all = repo.list().await.expect("list");
        assert_eq!(all.len(), 1);
        assert_eq!(all[0], created);
    }

    /// Each creation generates a distinct key (collision probability of 8-byte entropy is negligible).
    #[tokio::test]
    async fn create_generates_distinct_keys() {
        let repo = InMemoryApiKeyRepository::new();
        let a = CreateApiKeyUsecase
            .execute(&repo, input("a"))
            .await
            .expect("a");
        let b = CreateApiKeyUsecase
            .execute(&repo, input("b"))
            .await
            .expect("b");
        assert_ne!(a.key, b.key);
    }

    /// Create: a blank name (including whitespace-only) is rejected and not persisted.
    #[tokio::test]
    async fn create_rejects_blank_name() {
        let repo = InMemoryApiKeyRepository::new();
        let err = CreateApiKeyUsecase
            .execute(&repo, input("   "))
            .await
            .expect_err("blank name should be rejected");
        assert!(matches!(err, ApiKeyError::Validation(_)));
        assert!(repo.list().await.expect("list").is_empty());
    }

    /// Create: the name is trimmed before persisting.
    #[tokio::test]
    async fn create_normalizes_whitespace() {
        let repo = InMemoryApiKeyRepository::new();
        let created = CreateApiKeyUsecase
            .execute(&repo, input("  my-client  "))
            .await
            .expect("create");
        assert_eq!(created.name, "my-client");
    }

    /// Update: merges name / quota limit / enable state, keeps the key unchanged, upsert adds no new row.
    #[tokio::test]
    async fn update_merges_fields_and_keeps_key() {
        let repo = InMemoryApiKeyRepository::new();
        let created = CreateApiKeyUsecase
            .execute(&repo, input("my-client"))
            .await
            .expect("create");

        let updated = UpdateApiKeyUsecase
            .execute(
                &repo,
                created.id,
                ApiKeyInput {
                    name: "my-client-v2".to_string(),
                    quota_limit: None, // clear the limit
                    enabled: false,
                },
            )
            .await
            .expect("update");
        assert_eq!(updated.name, "my-client-v2");
        assert_eq!(updated.quota.limit, None);
        assert!(!updated.enabled);
        assert_eq!(updated.key, created.key, "更新不改变密钥");
        assert_eq!(
            updated.quota.used, created.quota.used,
            "已用额度不受编辑影响"
        );

        let all = repo.list().await.expect("list");
        assert_eq!(all.len(), 1, "upsert 不新增行");
        assert_eq!(all[0], updated);
    }

    /// Update / delete / enable-disable / accumulate: an unknown id returns NotFound.
    #[tokio::test]
    async fn mutate_unknown_id_errors_not_found() {
        let repo = InMemoryApiKeyRepository::new();
        let id = Uuid::now_v7();
        assert!(matches!(
            UpdateApiKeyUsecase.execute(&repo, id, input("x")).await,
            Err(ApiKeyError::NotFound)
        ));
        assert!(matches!(
            DeleteApiKeyUsecase.execute(&repo, id).await,
            Err(ApiKeyError::NotFound)
        ));
        assert!(matches!(
            SetApiKeyEnabledUsecase.execute(&repo, id, false).await,
            Err(ApiKeyError::NotFound)
        ));
        assert!(matches!(
            AccumulateUsageUsecase.execute(&repo, id, 10).await,
            Err(ApiKeyError::NotFound)
        ));
    }

    /// Delete: the list is empty after deletion, a second delete reports NotFound.
    #[tokio::test]
    async fn delete_removes_key_and_missing_errors() {
        let repo = InMemoryApiKeyRepository::new();
        let created = CreateApiKeyUsecase
            .execute(&repo, input("a"))
            .await
            .expect("create");

        DeleteApiKeyUsecase
            .execute(&repo, created.id)
            .await
            .expect("delete");
        assert!(repo.list().await.expect("list").is_empty());
        assert!(matches!(
            DeleteApiKeyUsecase.execute(&repo, created.id).await,
            Err(ApiKeyError::NotFound)
        ));
    }

    /// Enable-disable: false → true round-trip, state persisted correctly.
    #[tokio::test]
    async fn set_enabled_toggles_state() {
        let repo = InMemoryApiKeyRepository::new();
        let created = CreateApiKeyUsecase
            .execute(&repo, input("a"))
            .await
            .expect("create");

        let disabled = SetApiKeyEnabledUsecase
            .execute(&repo, created.id, false)
            .await
            .expect("disable");
        assert!(!disabled.enabled);

        let enabled = SetApiKeyEnabledUsecase
            .execute(&repo, created.id, true)
            .await
            .expect("enable");
        assert!(enabled.enabled);
    }

    /// List: returns all keys.
    #[tokio::test]
    async fn list_returns_all_keys() {
        let repo = InMemoryApiKeyRepository::new();
        CreateApiKeyUsecase
            .execute(&repo, input("a"))
            .await
            .expect("a");
        CreateApiKeyUsecase
            .execute(&repo, input("b"))
            .await
            .expect("b");

        let all = ListApiKeysUsecase.execute(&repo).await.expect("list");
        assert_eq!(all.len(), 2);
    }

    /// Accumulate: used is correct and persisted after accumulation; it accumulates across multiple calls.
    #[tokio::test]
    async fn accumulate_usage_adds_and_persists() {
        let repo = InMemoryApiKeyRepository::new();
        let created = CreateApiKeyUsecase
            .execute(&repo, input("a"))
            .await
            .expect("create");

        let after_first = AccumulateUsageUsecase
            .execute(&repo, created.id, 40)
            .await
            .expect("accumulate 40");
        assert_eq!(after_first.quota.used, 40);

        let after_second = AccumulateUsageUsecase
            .execute(&repo, created.id, 70)
            .await
            .expect("accumulate 70");
        assert_eq!(after_second.quota.used, 110);

        let found = repo
            .find_by_id(created.id)
            .await
            .expect("find")
            .expect("found");
        assert_eq!(found.quota.used, 110, "已用额度应持久化");
    }

    /// Accumulate: used keeps increasing past the limit (over-limit decisions are handled by QuotaPolicy / the auth use case, no silent truncation).
    #[tokio::test]
    async fn accumulate_usage_can_exceed_quota_limit() {
        let repo = InMemoryApiKeyRepository::new();
        let created = CreateApiKeyUsecase
            .execute(&repo, input("a"))
            .await
            .expect("create");

        let updated = AccumulateUsageUsecase
            .execute(&repo, created.id, 200)
            .await
            .expect("accumulate");
        assert_eq!(updated.quota.used, 200);
    }
}
